### ISSUE TITLE
yt-dlp.exe creates child processes that aren't killed when calling YoutubeDLP.CancelDownload()

### ISSUE THREAD

**Issue by GrumpyBear57** [Antfere/NYoutubeDLP#1]
I've been experiencing an issue where calling `.CancelDownload()` on a Twitch livestream download doesn't actually stop the download. After debugging for a couple hours, I believe the issue is due to the fact that yt-dlp.exe is creating child processes (see [here](https://github.com/yt-dlp/yt-dlp/issues/661) for information as to why), which NYoutubeDLP doesn't know about, and therefor doesn't kill when calling the internal `StopProcess()` method. 

For example, I have this code: 
```csharp
YoutubeDLP downloader = new YoutubeDLP(_config["YouTubeDL:ExecutablePath"]);
downloader.Options.FilesystemOptions.Output = outputFile;
downloader.DownloadAsync($"https://twitch.tv/{channel}");
await Task.Delay(TimeSpan.FromSeconds(10));
downloader.CancelDownload();
```

Stepping down into `SetupDownload()` from the `DownloadAsync()` call, I can see that `ydl.downloadProcessId` is being set to `441240`, which if I open Task Manager and locate that PID then right click > Analyze wait chain, I can see that there is a child process that is being waited on:
![image](https://user-images.githubusercontent.com/3745125/186070948-838a9174-dc6b-4397-993c-cd37ab9236bd.png)

Most of my testing has been on Twitch, though a quick test with a YouTube URL also shows that a child process is being created, and not cleaned up properly when cancelling. In this scenario, the download will stop, however the child process is still left as an orphan, and the file remains locked by it. 

I believe this could be fixed in NYTDLP by using the [`Process.Kill()` overload that takes a boolean to kill child processes](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.process.kill?view=net-6.0#system-diagnostics-process-kill(system-boolean)), however that isn't available on .NET Standard 2.0 (only .NET Core 3.0 and up), and I can understand if moving away from Standard isn't desirable. There doesn't seem to be an actual proper way to get child processes without [using the Windows-specific WMI](https://stackoverflow.com/a/1073697) (which might not even be implemented in Standard -- I'm not too sure how it works), and just finding processes with the executable in the name would probably be a bad idea since downloads can be run in parallel. 

If you're not concerned about moving away from .NET Standard, I can submit a PR to do that an use the `Process.Kill()` overload method. I'll continue looking to find some way to accomplish this without updating, but I'm not going to make any promises.

**Comment by Antfere** [comment]
Hello,

Sorry for the somewhat late reply, I just got this email, I haven't looked
through it yet but will do so as soon as possible. Thank you for your time.

**Comment by Antfere** [comment]
Hello,

I would like to thank you for your interest in the library, you seem to know more about it then I do! I have updated some of the options to a newer version of youtube-dlp, so if you can, fetch the changes and send in a pull request for your implementation. I would be glad to merge it for you.
